import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { GeneratedRoute } from '@/types/expedition'
import { formatDuration } from '@/lib/routing/naismith'

const BRAND_NAVY: [number, number, number] = [22, 48, 107]
const BRAND_TEAL: [number, number, number] = [30, 125, 107]

/**
 * Build a printable route card as a jsPDF document. Sections:
 * 1. Header (route name, date, branding)
 * 2. Overview (distance, ascent, descent, time, group size)
 * 3. Stage table (one row per day)
 * 4. Checkpoints table
 * 5. Emergency contacts
 * 6. Footer (generated-by + page numbers)
 *
 * Returns the jsPDF instance; the caller decides how to persist it
 * (`doc.output('arraybuffer')` in the main process, or `doc.save()` in tests).
 */
export function buildPdf(route: GeneratedRoute): jsPDF {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 40

  // 1. Header band.
  doc.setFillColor(...BRAND_NAVY)
  doc.rect(0, 0, pageWidth, 70, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.text('TrailTitan', margin, 34)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(12)
  doc.text(route.name, margin, 54)
  doc.setFontSize(9)
  doc.text(
    `Generated ${new Date(route.createdAt).toLocaleDateString()}${
      route.isMock ? '  ·  DEMO ROUTE' : ''
    }`,
    pageWidth - margin,
    54,
    { align: 'right' },
  )

  // 2. Overview.
  let y = 100
  doc.setTextColor(...BRAND_NAVY)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.text('Overview', margin, y)
  y += 16
  doc.setTextColor(40, 40, 40)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  const overview = [
    `Total distance: ${route.totalDistanceKm} km`,
    `Total ascent: ${route.totalAscentM} m`,
    `Total descent: ${route.totalDescentM} m`,
    `Estimated time: ${formatDuration(route.totalTimeMins)}`,
    `Days: ${route.stages.length}`,
    `Group size: ${route.config.groupSize.min}–${route.config.groupSize.max}`,
  ]
  overview.forEach((line, i) => {
    const col = i % 2
    const row = Math.floor(i / 2)
    doc.text(line, margin + col * 260, y + row * 16)
  })
  y += Math.ceil(overview.length / 2) * 16 + 16

  // 3. Stage table.
  autoTable(doc, {
    startY: y,
    head: [['Day', 'From', 'To', 'Distance (km)', 'Ascent (m)', 'Est. Time']],
    body: route.stages.map((s) => [
      String(s.day),
      s.from,
      s.to,
      s.distanceKm.toFixed(1),
      String(s.ascentM),
      formatDuration(s.estTimeMins),
    ]),
    headStyles: { fillColor: BRAND_TEAL, textColor: 255 },
    styles: { fontSize: 9, cellPadding: 5 },
    margin: { left: margin, right: margin },
  })
  y = lastTableY(doc) + 24

  // 4. Checkpoints.
  if (route.config.checkpoints.length > 0) {
    doc.setTextColor(...BRAND_NAVY)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.text('Checkpoints', margin, y)
    autoTable(doc, {
      startY: y + 8,
      head: [['Name', 'Coordinates (lat, lng)', 'Arrival window']],
      body: route.config.checkpoints.map((c) => [
        c.name,
        `${c.coordinates[1].toFixed(4)}, ${c.coordinates[0].toFixed(4)}`,
        c.arrivalWindow
          ? `${c.arrivalWindow.earliest}–${c.arrivalWindow.latest}`
          : '—',
      ]),
      headStyles: { fillColor: BRAND_TEAL, textColor: 255 },
      styles: { fontSize: 9, cellPadding: 5 },
      margin: { left: margin, right: margin },
    })
    y = lastTableY(doc) + 24
  }

  // 5. Emergency contacts.
  if (route.config.emergencyContacts.length > 0) {
    doc.setTextColor(...BRAND_NAVY)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.text('Emergency contacts', margin, y)
    autoTable(doc, {
      startY: y + 8,
      head: [['Name', 'Role', 'Phone']],
      body: route.config.emergencyContacts.map((c) => [c.name, c.role, c.phone]),
      headStyles: { fillColor: BRAND_NAVY, textColor: 255 },
      styles: { fontSize: 9, cellPadding: 5 },
      margin: { left: margin, right: margin },
    })
  }

  // 6. Footer with page numbers.
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    const h = doc.internal.pageSize.getHeight()
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(120, 120, 120)
    doc.text('Generated by TrailTitan', margin, h - 20)
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, h - 20, {
      align: 'right',
    })
  }

  return doc
}

/** jspdf-autotable stores the final Y on the doc; read it defensively. */
function lastTableY(doc: jsPDF): number {
  const last = (doc as unknown as { lastAutoTable?: { finalY: number } })
    .lastAutoTable
  return last?.finalY ?? 120
}
