import type { GeneratedRoute } from '@/types/expedition'
import { formatDuration } from '@/lib/routing/naismith'
import { Logo } from '@/components/Brand'

/** On-screen route card that mirrors the exported PDF layout. */
export function RouteReport({ route }: { route: GeneratedRoute }) {
  return (
    <div className="mx-auto max-w-3xl space-y-6 rounded-lg border bg-card p-6 shadow-sm print:border-0 print:shadow-none">
      <header className="flex items-center justify-between border-b pb-4">
        <div>
          <Logo className="h-7" />
          <h1 className="mt-2 text-xl font-semibold">{route.name}</h1>
          <p className="text-xs text-muted-foreground">
            Generated {new Date(route.createdAt).toLocaleString()}
            {route.isMock && ' · DEMO ROUTE'}
          </p>
        </div>
      </header>

      <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <Stat label="Distance" value={`${route.totalDistanceKm} km`} />
        <Stat label="Ascent" value={`${route.totalAscentM} m`} />
        <Stat label="Descent" value={`${route.totalDescentM} m`} />
        <Stat label="Est. time" value={formatDuration(route.totalTimeMins)} />
      </section>

      <section>
        <h2 className="mb-2 text-sm font-semibold">Stages</h2>
        <div className="overflow-hidden rounded-md border">
          <table className="w-full text-sm">
            <thead className="bg-muted text-left text-xs uppercase text-muted-foreground">
              <tr>
                <th className="p-2">Day</th>
                <th className="p-2">From</th>
                <th className="p-2">To</th>
                <th className="p-2 text-right">Distance</th>
                <th className="p-2 text-right">Ascent</th>
                <th className="p-2 text-right">Est. time</th>
              </tr>
            </thead>
            <tbody>
              {route.stages.map((s) => (
                <tr key={s.day} className="border-t">
                  <td className="p-2">{s.day}</td>
                  <td className="p-2">{s.from}</td>
                  <td className="p-2">{s.to}</td>
                  <td className="p-2 text-right tabular-nums">
                    {s.distanceKm.toFixed(1)} km
                  </td>
                  <td className="p-2 text-right tabular-nums">{s.ascentM} m</td>
                  <td className="p-2 text-right tabular-nums">
                    {formatDuration(s.estTimeMins)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {route.config.checkpoints.length > 0 && (
        <section>
          <h2 className="mb-2 text-sm font-semibold">Checkpoints</h2>
          <ul className="space-y-1 text-sm">
            {route.config.checkpoints.map((c) => (
              <li key={c.id} className="flex justify-between border-b py-1">
                <span>{c.name}</span>
                <span className="text-muted-foreground">
                  {c.arrivalWindow
                    ? `${c.arrivalWindow.earliest}–${c.arrivalWindow.latest}`
                    : `${c.coordinates[1].toFixed(4)}, ${c.coordinates[0].toFixed(4)}`}
                </span>
              </li>
            ))}
          </ul>
        </section>
      )}

      {route.config.emergencyContacts.length > 0 && (
        <section>
          <h2 className="mb-2 text-sm font-semibold">Emergency contacts</h2>
          <ul className="space-y-1 text-sm">
            {route.config.emergencyContacts.map((c, i) => (
              <li key={i} className="flex justify-between border-b py-1">
                <span>
                  {c.name} <span className="text-muted-foreground">· {c.role}</span>
                </span>
                <span className="tabular-nums">{c.phone}</span>
              </li>
            ))}
          </ul>
        </section>
      )}

      <footer className="border-t pt-3 text-center text-xs text-muted-foreground">
        Generated by TrailTitan
      </footer>
    </div>
  )
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-md border bg-muted/40 p-3">
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className="text-lg font-semibold">{value}</p>
    </div>
  )
}
